### ISSUE TITLE
HTML Externals

### ISSUE THREAD

**Issue by stoically** [FlorianRappl/parcel-plugin-externals#2]
Just a quick thought, since I'm using the `externals` key in [`parcel-plugin-html-externals`](https://github.com/stoically/parcel-plugin-html-externals) as well, that might introduce conflicts in case someone wanted to use both packages. Would you be interested in merging or introducing HTML support here?

**Comment by FlorianRappl** [comment]
Great catch.

Any suggestions for the resolution of the conflict?

Merging could of course work, but potentially having the granularity to choose (opt-in) would be good, too.

From the top of my head I have two suggestions:

- I rename `externals` to `externalDependencies` (since this library is younger)
- We both keep `externals` and I ignore keys with a boolean value (while you ignore keys with a string value) // not sure here if you handle string values at the moment

@stoically

**Comment by stoically** [comment]
> We both keep externals and I ignore keys with a boolean value (while you ignore keys with a string value)

Good suggestion, hadn't thought about that. I'll change the [falsy check](https://github.com/stoically/parcel-plugin-html-externals/blob/a699690748ab464feed0c7fb99ee2bfd1d3bbd87/src/HTMLExternalsAsset.js#L32) to `=== false`, since `false` is the only value I handle anyway.

If that works for you as well, that'd be great. Feel free to close the issue.

**Comment by FlorianRappl** [comment]
Awesome - thanks for the hint. I'll leave it open until 0.2 is shipped (in this version I'll ignore values with 'false' - I will also update the documentation and mention `parcel-plugin-html-externals`).
