### ISSUE TITLE
Uncaught ReferenceError: React is not defined

### ISSUE THREAD

**Issue by olegulbrandsen** [FlorianRappl/parcel-plugin-externals#23]
I'm able to exclude react from the build using "parcel-plugin-externals". 

However, when I dynamically load the compiled script file into another project that already is using react, I get the error message "Uncaught ReferenceError: React is not defined". How do I make the script load the excluded module from the script it is being loaded into?

 ( If that make sense to you, I realize this is a very incomplete description )

-----

More details on what I'm trying to do:

We are building a SPA application for a CMS using react, parcel and typescript. 
We want to build a plugin system that will allow third party developers to create their own controls that plug into the CMS UI. These ui components must be loaded dynamically and from external sources. 

We distribute our CMS components to NPMJS and third party developers will develop their plugins by referencing the NPM modules. The output of these projects should only contain the custom code they have written. I'm trying to use Parcel with "parcel-plugin-externals" to build a script file that can be loaded dynamically into the CMS at runtime. 

To load the script file with:

```
const loadedScrips: Set<string> = new Set();
async function loadScript(url: string): Promise<void> {
    if (loadedScrips.has(url)) return;
    loadedScrips.add(url);
    return new Promise((resolve, reject) => {
        var script = document.createElement('script');
        script.onload = () => resolve();
        script.onerror = (err) => reject(err);
        script.src = url;
        document.head.appendChild(script);
    });
}
```

In the package,json we have added:
```
  "externals": {
    "react": "React"
  },

```
Without the "externals" it works, with the "externals" section it fails with: 
"Uncaught ReferenceError: React is not defined"

If you want, I could make a simplified example and upload it to github.

Any help with the matter is greatly appreciated !

**Comment by FlorianRappl** [comment]
Externalizing means that you somehow need to provide it. There are multiple ways to do it, however, since Parcel does not have a standard mechanism we cannot decide here (btw: the same applies to webpack if no specific mechanism such as DLL or module federation is used).

If you say "React" we assume an object `React` exists on `window`. So you need to make sure that `window.React` exists.

The README also lists a couple other examples incl. custom locations such as `window.dependencies.React`.

One way of resolving the need above is to just write `window.React = require('react')`**before** the script with the externalized React is imported.

Hope that helps!

**Comment by olegulbrandsen** [comment]
Thanks, that did help. We got it working by setting window.React = require('react'). I was not sure how to make "external" packages available to the plugin that was compiled without it. But now I know! :-) Thanks

**Comment by FlorianRappl** [comment]
Sure - always @olegulbrandsen !

Happy hacking! :beers:
