### ISSUE TITLE
Can't tell if plugin is running

### ISSUE THREAD

**Issue by chisholmd** [FlorianRappl/parcel-plugin-externals#26]
I am using Parcel 1.12.4 which is installed globally.
I installed this plugin globally
`  npm install  -g  parcel-plugin-externals`

I ran into this error message:
`'Error: Cannot find module 'parcel-bundler/src/Logger'`

But I think I resolved it by adding some missing files as per
https://stackoverflow.com/questions/62870976/parcel-plugin-transcrypt-fails-with-error-cannot-find-module-parcel-bundler-s

I added the following to my package.json but I am not confident that I did it correctly.
```
 "externals": [
    "userConfig"
  ],
  "alias": {
    "userConfig": "../config/user_config.js"
  }
```
When I run my parcel build I can not see if the plugin is working, but my desired end result is definitely not working.

I think I have an incredibly simple use case.  I have an external file that I want to import manually and I want Parcel to ignore it.  I want my import statement to remain exactly as it is:
At run time if I perform
`   import('../config/user_config.js')`

I want it to read that actual file on in that location and not be redirected to some bundled code.

Am I asking too much?

**Comment by FlorianRappl** [comment]
First of all `parcel` should not be globally installed. Always install your dependencies locally. Second, Parcel resolves plugins by looking at the package.json. So if your local package.json does not list this package in the `devDependencies` it will not work.

Your code will not work anyway. You define two things, `externals` and `alias`. Now I am confused, because if `alias` is resolved then Parcel will bundle `../config/user_config.js`. If `externals` is resolved then just nothing will be done. Why don't you just use a `fetch` if you want to resolve at runtime?

What you could do is to specify how the externals are retrieved. Instead of resolving the external via `window` I guess in your case you'd want some custom logic to load the script and return its result.

**Comment by chisholmd** [comment]
Using Fetch at runtime is a very very excellent idea.  I was suffering from tunnel vision trying to figure out how to not bundle the file. 👍
