### ISSUE TITLE
Question: Is there a way to set all modules to be externals?

### ISSUE THREAD

**Issue by mfasman95** [FlorianRappl/parcel-plugin-externals#4]
I am currently working with `webpack` and considering looking into adoption of `parcel` for a variety of reasons. So far, externals seems to be the primary feature that is missing when considering this adoption. We need to leverage externals in two different ways. I wanted to know if this plugin currently supports our two use cases and, if not, whether it would be possible to add this support.

First use case: typical `webpack` externals. This is the normal use case and the one I am fairly certain is supported. In a situation where I am developing a single page application and I know that `jQuery` will be available globally I can list it as an external and not include it in the application's bundle.

Second use case: marking all `node_modules` as externals. This is the use case I am not as confident is supported. We develop a number of internal libraries and we know for a fact that the dependencies of those libraries will be downloaded by the applications that consume those libraries. Therefore, whenever we bundle a library, we list all of its dependencies as externals using a library designed for webpack - [`webpack-node-externals`](https://www.npmjs.com/package/webpack-node-externals). Is it possible to mimic this behavior using this plugin?

**Comment by FlorianRappl** [comment]
Hm great question (and potential addition). Right now the externals are only determined by the `peerDependencies` and the `externals` (if used).

Maybe we could do the following regarding the `externals`: For each key we check if wildcards (*) are used. Additionally, we can check if slashes (/) are used - leading to paths.

Examples:

- `react-*` would lead to all packages starting with `react-`
- `./node_modules/react-*` would lead to all packages located in `node_modules` that start with `react`
- `./node_modules/*` would lead to all packages located in `node_modules`

The replacement rule then could be complicated... Suggestions are defined replacement variables such as `$1` (replaced string), `$u` (replaced string uppercase) etc.

Would be happy to hear how you solve it at the moment and what kind of syntax / options you could image for this feature!

**Comment by mfasman95** [comment]
I think the examples you had there for `$1` and `$u` sound like a good way to go.

**Comment by stoically** [comment]
RegExp could maybe help, since e.g. `"foobar".replace(/(foo)(bar)/, '$2$1'); // barfoo`

**Comment by FlorianRappl** [comment]
How is that connected to the problem @stoically (maybe I'm missing something)?

Note that the configuration is done in a JSON. Once a wildcard is detected a regex would be used underneath, hence the syntax for defining the replacement on the RHS.

**Comment by stoically** [comment]
Since you were talking about wildcards, it wasn't clear to me that you had RegExp already in mind, sorry about that.

I was just thinking that it might be easy to implement to have a special syntax to designate the LHS as RegExp, and use the RHS as appropriate replacement string in that case. Maybe if the LHS matches `/^\/(.*)\/([gimsuy]+)?$/` it could be treated as RegExp, e.g. `"/my(regexp)/": "your$1"`

**Comment by FlorianRappl** [comment]
Problem with a syntax like `/foo/` is that it excludes paths. The other problem that I see is the level of verbosity and difficulty of reading, e.g., having slashes would require a backslash, but since that already has a meaning in a string two backslashes would be needed.

Anyway since the LHS would be primarily file based I wanted to opt-in for glob patterns, which just work as strings and are pretty well established. The only problem is that the RHS needs additional variables to cover the complexity of transformation (e.g., `react` to `React`).

In general the replacement for wildcards would be a problem that is hard to solve in my opinion (the `$u` for making an uppercase version of the standard `$1` was one trial, but there are countless other cases...). One other option here on the RHS is that a relative file path to a Node.js module could be taken, which exports a function returning that string.

Another radical solution that takes both - a simpler RHS and allowing a regular expression on the LHS  is that externals are defined in a Node.js module already. If `externals` is a string it would be evaluated as a (relative) path to a Node.js module; which exports a function that gets the requested module name (plus its path etc.) and either returns undefined (-> no external) or a string (replacement).

**Comment by FlorianRappl** [comment]
Landed in `develop` and was published as a preview.

Current implementation:
Besides the "standard" ways of declaring externals you can also give it a string, e.g.,

```json
{
  "externals": "./tools/ruleFactory.js"
}
```

The rule factory module is just a simple Node.js module that exports a function:

```js
const rx = /node_modules\/react-(.*?)\//;

module.exports = function(path) {
  const result = rx.exec(path);

  if (result) {
    const suffix = result[1];
    const name = suffix[0].toUpperCase() + suffix.substr(1);
    return `react-${suffix} => React${name}`;
  }

  return undefined;
};
```

Essentially, you just return what would usually be in your hands. Since you get full paths you have flexibility, however, that comes with "responsibility".

Let me know what you think!

**Comment by FlorianRappl** [comment]
Will be published in v3.
